pipeline {
    agent any

    stages {
       
         stage('MavenClean') {
            steps {
                dir("Modularframework-29112022") {
                powershell 'mvn clean'
                  }
             }
        }
         stage('MavenTest') {
            steps {
                dir("Modularframework-29112022") {
             powershell 'mvn test'
                  }
             }
        }
    }
}
